### ISSUE TITLE
navigateAfterFuture isn’t available on pub.dev

### ISSUE THREAD

**Issue by cvlnomen** [KarimMohamed20/SplashScreenFlutterPackage#48] opened 2020-10-23 17:56 UTC
**Describe the bug**
The version of the SplashScreen package available on pub.dev is not the latest GitHub version and therefore does not contain “navigateAfterFuture”.

**To Reproduce**
1. Create a new flutter project.
2. Go to pubspec.yaml and add “splashscreen: ^1.2.0” or just “splashscreen: ”
3. Try to add a new SplashScreen object with the “navigateAfterFuture” field.

**Expected behavior**
The pub.dev version of the package should be the latest GitHub version.

**Workaround**
Use the latest GitHub version of the package instead of the pub.dev one, by adding the following to your pubspec.yaml file:

`splashscreen:`
     `  git:`
       `  url: https://github.com/KarimMohamed2005/SplashScreenFlutterPackage.git`
      `   ref: master`

**Comment by ahmedmgh67** [comment] 2020-10-28 09:44
Hello Chris, 
So sorry for this issue, we already know it and we're trying to solve it as fast as possible, the problem is that the main uploader @KarimMohamed20  faces issue when he's trying to authenticate into the CLI to upload the new version. Sorry for what's happening.
I'm not closing so that anyone that face this issue can see it easily and solve it with your workaround
Thank you

**Comment by KarimMohamed20** [comment] 2020-11-04 11:45
Currently navigateAfterFuture is working great ❤️
Sorry for being late.

**Closed by KarimMohamed20** 2020-11-04 11:45 UTC
